on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set Repo Envs
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}')
          echo "git_repo_name=${REPO_NAME}" | tee -a $GITHUB_ENV
          echo "node_version=14.x" | tee -a $GITHUB_ENV
          echo "mongodb_version=4.0" | tee -a $GITHUB_ENV
          
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: '${{ env.node_version }}'

      - name: Start MongoDB ${{ env.node_version }}
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ env.mongodb_version }}
          mongodb-username: root
          mongodb-password: example
          mongodb-db: ${{ env.git_repo_name }}_test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install and test
        id: npm-install-test
        run: |
          aws codeartifact login --tool npm --repository perfectmatch-core --domain talent-fabric
          npm install
          npm run test